{
    "debug_mode": "1",
    "site_url": "/",
    "contact_mail": "alexeytarutin@gmail.com",
    "site_name": "FEO",
    "domain": "app.feo.finance",
    "mail_robot": "robot",
    "default_template": "default",
    "tpl_show_undef_vars": "0",
    "db_name": "app",
    "db_prefix": "feo_",
    "db_host": "localhost",
    "db_user": "app",
    "db_password": "",
    "backoffice_url": "back",
    "clear_html": "1",
    "cookie_lifetime": "31104000",
    "admin_templates": "back",
    "memcache_host": "localhost",
    "memcache_port": "11211",
    "memcache_global_prefix": "feo"
}
